name: proportal_app
description: "自分専用の日記作成アプリです"

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod:
  riverpod_annotation: 

  freezed:
  freezed_annotation:   

  go_router:

  firebase_core: 
  firebase_auth:
  cloud_firestore:

  firebase_remote_config: 

  web:  

  google_fonts: 


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner:
  riverpod_generator:

  json_serializable: 

flutter:
  uses-material-design: true

 
